### ISSUE TITLE
server not starting - crash

### ISSUE THREAD

**Issue by 0gp** [PlanetTeamSpeakk/MoreCommands#53]
MC 1.17.1
FABRIC Loader 0.12.12
FABRIC API 0.44.0
MoreCommands-3.9_1.16.4-1.18.1
```
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: net/minecraft/class_793
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:610)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_793
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3334)
	at java.base/java.lang.Class.getMethodsRecursive(Class.java:3475)
	at java.base/java.lang.Class.getMethod0(Class.java:3461)
	at java.base/java.lang.Class.getMethod(Class.java:2193)
	at com.ptsmods.morecommands.util.ReflectionHelper.getMethod(ReflectionHelper.java:80)
	at com.ptsmods.morecommands.util.ReflectionHelper.getYarnMethod(ReflectionHelper.java:72)
	at com.ptsmods.morecommands.MoreCommands.lambda$onInitialize$5(MoreCommands.java:170)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.ptsmods.morecommands.MoreCommands.lambda$onInitialize$6(MoreCommands.java:157)
	at com.ptsmods.morecommands.callbacks.PostInitCallback.lambda$static$0(PostInitCallback.java:8)
	at net.minecraft.server.Main.handler$edp000$postInitNew(Main.java:2523)
	at net.minecraft.server.Main.main(Main.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_793
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 25 more

```

**Comment by PlanetTeamSpeakk** [comment]
Seems like the mod attempts to load a client-only class on the server side, this is a bug.

**Comment by PlanetTeamSpeakk** [comment]
Fixed in upcoming release.
