### ISSUE TITLE
[1.17.1] what is mm? Mod 'MoreCommands' (morecommands) 3.9.2 requires version 2.3 or later of mm, which is missing!

### ISSUE THREAD

**Issue by MSandro** [PlanetTeamSpeakk/MoreCommands#57]
not sure, maybe I am stupid but I can not find the dependency named MM in the mod description.

```
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install mm, version 2.3 or later.
Unmet dependency listing:
	 - Mod 'MoreCommands' (morecommands) 3.9.2 requires version 2.3 or later of mm, which is missing!
Inactive mods:
	 - mod 'Advancements Enlarger' (advancements-enlarger) 0.2.4, reason: wrong environment (client/server only)
	 - mod 'Break Progress' (breakprogress) 1.0.1, reason: wrong environment (client/server only)
	 - mod 'Better Sodium Video Settings Button' (bsvsb) 2.0.4, reason: wrong environment (client/server only)
	 - mod 'cAn i MiNe thIS bLOCk?' (can-i-mine-this-block) 1.1.0, reason: wrong environment (client/server only)
	 - mod 'Disable Custom Worlds Advice' (disable_custom_worlds_advice) 1.4, reason: wrong environment (client/server only)
	 - mod 'Enhanced Block Entities' (enhancedblockentities) 0.5+1.17, reason: wrong environment (client/server only)
	 - mod 'I Know What I'm Doing' (iknowwhatimdoing) 4.0.0, reason: wrong environment (client/server only)
	 - mod 'Konkrete' (konkrete) 1.3.0, reason: wrong environment (client/server only)
	 - mod 'Light Overlay' (lightoverlay) 6.0.1, reason: wrong environment (client/server only)
	 - mod 'Mod Menu' (modmenu) 2.0.14, reason: wrong environment (client/server only)
	 - mod 'MoreTooltips' (more_tooltips) 1.0.2, reason: wrong environment (client/server only)
	 - mod 'Mouse Tweaks' (mousetweaks) 2.15, reason: wrong environment (client/server only)
	 - mod 'No Potion Offset' (no-potion-offset) ${version}, reason: wrong environment (client/server only)
	 - mod 'Ok Zoomer' (okzoomer) 5.0.0-beta.3+1.17.1, reason: wrong environment (client/server only)
	 - mod 'Pling' (pling) 1.5.0, reason: wrong environment (client/server only)
	 - mod 'Reese's Sodium Options' (reeses-sodium-options) 1.2.3, reason: wrong environment (client/server only)
	 - mod 'WMITAF' (wmitaf) 1.2.0, reason: wrong environment (client/server only)
	 - mod 'Runtime Resource Pack' (advanced_runtime_resource_pack) 0.2.9, reason: newer version active
	 - mod 'Runtime Resource Pack' (advanced_runtime_resource_pack) 0.3.7, reason: newer version active
	 - mod 'Auto Config v1 Updated' (autoconfig1u) 3.2.2, reason: newer version active
	 - mod 'jankson' (blue_endless_jankson) 1.2.1, reason: same version active
	 - mod 'jankson' (blue_endless_jankson) 1.2.1, reason: same version active
	 - mod 'Cardinal Components API (base)' (cardinal-components-base) 3.0.0-nightly.1.17-pre1, reason: newer version active
	 - mod 'Cardinal Components API (base)' (cardinal-components-base) 3.0.0-nightly.1.17-pre2, reason: newer version active
	 - mod 'Cardinal Components API (base)' (cardinal-components-base) 3.0.0, reason: newer version active
	 - mod 'Cardinal Components API (blocks)' (cardinal-components-block) 3.0.0, reason: newer version active
	 - mod 'Cardinal Components API (entities)' (cardinal-components-entity) 3.0.0-nightly.1.17-pre1, reason: newer version active
	 - mod 'Cardinal Components API (entities)' (cardinal-components-entity) 3.0.0-nightly.1.17-pre2, reason: newer version active
	 - mod 'Cardinal Components API (entities)' (cardinal-components-entity) 3.0.0, reason: newer version active
	 - mod 'Cardinal Components API (utilities)' (cardinal-components-util) 3.0.0-nightly.1.17-pre2, reason: newer version active
	 - mod 'Cardinal Components API (worlds)' (cardinal-components-world) 3.0.0, reason: newer version active
	 - mod 'Cloth Basic Math' (cloth-basic-math) 0.5.1, reason: newer version active
	 - mod 'Cloth Common Events v1' (cloth-common-events-v1) 1.5.47, reason: newer version active
	 - mod 'Cloth Config v6' (cloth-config) 6.1.48, reason: unknown
	 - mod 'Cloth Config v4' (cloth-config2) 4.11.18, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 5.0.33, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 5.0.34, reason: newer version active
	 - mod 'Cloth Config v5' (cloth-config2) 5.0.38, reason: newer version active
	 - mod 'Cloth Scissors API v1' (cloth-scissors-api-v1) 2.0.54, reason: wrong environment (client/server only)
	 - mod 'core' (com_electronwill_night-config_core) 3.6.2, reason: newer version active
	 - mod 'core' (com_electronwill_night-config_core) 3.6.3, reason: newer version active
	 - mod 'core' (com_electronwill_night-config_core) 3.6.5, reason: same version active
	 - mod 'toml' (com_electronwill_night-config_toml) 3.6.2, reason: newer version active
	 - mod 'toml' (com_electronwill_night-config_toml) 3.6.3, reason: newer version active
	 - mod 'toml' (com_electronwill_night-config_toml) 3.6.5, reason: same version active
	 - mod 'toml4j' (com_moandjiezana_toml_toml4j) +, reason: newer version active
	 - mod 'Custom Portal Api' (customportalapi) 0.0.1-beta45-1.17, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.1.3+12a8474cfa, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.1.3+12a8474c34, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b446318, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b446313, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b446318, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.0+5847535018, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.0+cf39a74318, reason: same version active
	 - mod 'Fabric BlockRenderLayer Registration (v1)' (fabric-blockrenderlayer-v1) 1.1.6+cf39a74318, reason: wrong environment (client/server only)
	 - mod 'Fabric Command API (v1)' (fabric-command-api-v1) 1.1.2+6cefd57718, reason: newer version active
	 - mod 'Fabric Command API (v1)' (fabric-command-api-v1) 1.1.3+5ab9934c18, reason: newer version active
	 - mod 'Fabric Entity Events (v1)' (fabric-entity-events-v1) 1.2.0+8a9f12e018, reason: newer version active
	 - mod 'Fabric Entity Events (v1)' (fabric-entity-events-v1) 1.2.1+077fc48418, reason: newer version active
	 - mod 'Fabric Item API (v1)' (fabric-item-api-v1) 1.2.4+a02b446318, reason: newer version active
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.4+a02b446318, reason: wrong environment (client/server only)
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.6+2a2bb57318, reason: wrong environment (client/server only)
	 - mod 'Fabric Key Bindings (v0)' (fabric-keybindings-v0) 0.2.4+cf39a74318, reason: wrong environment (client/server only)
	 - mod 'Fabric Lifecycle Events (v1)' (fabric-lifecycle-events-v1) 1.4.4+a02b446318, reason: newer version active
	 - mod 'Fabric Models (v0)' (fabric-models-v0) 0.3.1+cf39a74318, reason: wrong environment (client/server only)
	 - mod 'Fabric Networking API (v1)' (fabric-networking-api-v1) 1.0.14+cf39a74318, reason: newer version active
	 - mod 'Fabric Networking (v0)' (fabric-networking-v0) 0.3.2+92519afa13, reason: newer version active
	 - mod 'Fabric Renderer API (v1)' (fabric-renderer-api-v1) 0.4.5+cf39a74318, reason: wrong environment (client/server only)
	 - mod 'Fabric Renderer - Indigo' (fabric-renderer-indigo) 0.4.9+cf39a74318, reason: wrong environment (client/server only)
	 - mod 'Fabric Renderer Registries (v1)' (fabric-renderer-registries-v1) 3.2.6+cf39a74318, reason: wrong environment (client/server only)
	 - mod 'Fabric Rendering (v0)' (fabric-rendering-v0) 1.1.7+cf39a74318, reason: wrong environment (client/server only)
	 - mod 'Fabric Rendering (v1)' (fabric-rendering-v1) 1.6.0+a02b446318, reason: wrong environment (client/server only)
	 - mod 'Fabric Rendering (v1)' (fabric-rendering-v1) 1.10.1+377137cc18, reason: wrong environment (client/server only)
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.7+b7ab612118, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.10+f09604ce18, reason: same version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.5+cf39a74318, reason: wrong environment (client/server only)
	 - mod 'Fabric Tag Extensions (v0)' (fabric-tag-extensions-v0) 1.2.3+cf39a74318, reason: same version active
	 - mod 'Fabric Textures (v0)' (fabric-textures-v0) 1.0.7+cf39a74318, reason: wrong environment (client/server only)
	 - mod 'Hologram API' (hologram-api) 0.2.0+1.17.1, reason: newer version active
	 - mod 'libaddict' (libaddict) 0.3.0, reason: wrong environment (client/server only)
	 - mod 'LibBlockAttributes' (libblockattributes) 0.8.17003, reason: newer version active
	 - mod 'LibBlockAttributes (Core)' (libblockattributes_core) 0.8.17003, reason: newer version active
	 - mod 'LibBlockAttributes (Core)' (libblockattributes_core) 0.9.0, reason: same version active
	 - mod 'LibBlockAttributes (Fluids)' (libblockattributes_fluids) 0.8.17003, reason: newer version active
	 - mod 'LibBlockAttributes (Fluids)' (libblockattributes_fluids) 0.9.0, reason: same version active
	 - mod 'LibBlockAttributes (Items)' (libblockattributes_items) 0.8.17003, reason: newer version active
	 - mod 'LibBlockAttributes (Items)' (libblockattributes_items) 0.9.0, reason: same version active
	 - mod 'LibCapableData' (libcd) 3.0.3+1.16.3, reason: same version active
	 - mod 'LibGui' (libgui) 4.1.0+1.17, reason: newer version active
	 - mod 'LibGui' (libgui) 4.1.1+1.17.1-rc1, reason: newer version active
	 - mod 'LibGui' (libgui) 4.1.2+1.17.1, reason: newer version active
	 - mod 'LibGui' (libgui) 4.1.3+1.17.1, reason: newer version active
	 - mod 'LibGui' (libgui) 4.1.4+1.17.1, reason: newer version active
	 - mod 'LibGui' (libgui) 4.1.6+1.17.1, reason: newer version active
	 - mod 'LibGui' (libgui) 4.2.1+1.17.1, reason: newer version active
	 - mod 'Magna' (magna) 0.4.0-1.17.1, reason: newer version active
	 - mod 'megane-dml-simulacrum' (megane-dml-simulacrum) 5.6.1+1.0.5, reason: unknown
	 - mod 'Myron' (myron) 1.6.1-1.17.1, reason: newer version active
	 - mod 'OmegaConfig' (omega-config) 1.0.4, reason: newer version active
	 - mod 'OmegaConfig' (omega-config) 1.0.4, reason: newer version active
	 - mod 'Packet Tweaker' (packet_tweaker) 0.2.0-1.17-pre1, reason: newer version active
	 - mod 'Patchouli' (patchouli) 1.17.1-56-FABRIC, reason: newer version active
	 - mod 'Patchouli' (patchouli) 1.17.1-56-FABRIC-SNAPSHOT, reason: newer version active
	 - mod 'Fabric Placeholder API' (placeholder-api) 1.0.1+1.17, reason: newer version active
	 - mod 'Pal' (playerabilitylib) 1.3.0-nightly.1.17-pre1, reason: newer version active
	 - mod 'Pal' (playerabilitylib) 1.3.0-nightly.1.17-rc1, reason: newer version active
	 - mod 'Pal' (playerabilitylib) 1.3.0, reason: newer version active
	 - mod 'Pal' (playerabilitylib) 1.4.0, reason: same version active
	 - mod 'Reborn Core' (reborncore) 5.0.11-beta, reason: same version active
	 - mod 'Server Translations API' (server_translations_api) 1.4.5+1.17, reason: newer version active
	 - mod 'Somnus API' (somnus) 0.0.13-1.17.1, reason: newer version active
	 - mod 'Statement Vanilla Compatibility Module' (statement_vanilla_compatibility) 1.0.1+1.14.4-1.15.2, reason: newer version active
	 - mod 'Step Height Entity Attribute' (step-height-entity-attribute) 1.0.0, reason: same version active
	 - mod 'Energy' (team_reborn_energy) 0.1.1, reason: newer version active
	 - mod 'Trinkets' (trinkets) 3.0.4, reason: same version active
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install mm, version 2.3 or later.
Unmet dependency listing:
	 - Mod 'MoreCommands' (morecommands) 3.9.2 requires version 2.3 or later of mm, which is missing!
Inactive mods:
	 - mod 'Advancements Enlarger' (advancements-enlarger) 0.2.4, reason: wrong environment (client/server only)
	 - mod 'Break Progress' (breakprogress) 1.0.1, reason: wrong environment (client/server only)
	 - mod 'Better Sodium Video Settings Button' (bsvsb) 2.0.4, reason: wrong environment (client/server only)
	 - mod 'cAn i MiNe thIS bLOCk?' (can-i-mine-this-block) 1.1.0, reason: wrong environment (client/server only)
	 - mod 'Disable Custom Worlds Advice' (disable_custom_worlds_advice) 1.4, reason: wrong environment (client/server only)
	 - mod 'Enhanced Block Entities' (enhancedblockentities) 0.5+1.17, reason: wrong environment (client/server only)
	 - mod 'I Know What I'm Doing' (iknowwhatimdoing) 4.0.0, reason: wrong environment (client/server only)
	 - mod 'Konkrete' (konkrete) 1.3.0, reason: wrong environment (client/server only)
	 - mod 'Light Overlay' (lightoverlay) 6.0.1, reason: wrong environment (client/server only)
	 - mod 'Mod Menu' (modmenu) 2.0.14, reason: wrong environment (client/server only)
	 - mod 'MoreTooltips' (more_tooltips) 1.0.2, reason: wrong environment (client/server only)
	 - mod 'Mouse Tweaks' (mousetweaks) 2.15, reason: wrong environment (client/server only)
	 - mod 'No Potion Offset' (no-potion-offset) ${version}, reason: wrong environment (client/server only)
	 - mod 'Ok Zoomer' (okzoomer) 5.0.0-beta.3+1.17.1, reason: wrong environment (client/server only)
	 - mod 'Pling' (pling) 1.5.0, reason: wrong environment (client/server only)
	 - mod 'Reese's Sodium Options' (reeses-sodium-options) 1.2.3, reason: wrong environment (client/server only)
	 - mod 'WMITAF' (wmitaf) 1.2.0, reason: wrong environment (client/server only)
	 - mod 'Runtime Resource Pack' (advanced_runtime_resource_pack) 0.2.9, reason: newer version active
	 - mod 'Runtime Resource Pack' (advanced_runtime_resource_pack) 0.3.7, reason: newer version active
	 - mod 'Auto Config v1 Updated' (autoconfig1u) 3.2.2, reason: newer version active
	 - mod 'jankson' (blue_endless_jankson) 1.2.1, reason: same version active
	 - mod 'jankson' (blue_endless_jankson) 1.2.1, reason: same version active
	 - mod 'Cardinal Components API (base)' (cardinal-components-base) 3.0.0-nightly.1.17-pre1, reason: newer version active
	 - mod 'Cardinal Components API (base)' (cardinal-components-base) 3.0.0-nightly.1.17-pre2, reason: newer version active
	 - mod 'Cardinal Components API (base)' (cardinal-components-base) 3.0.0, reason: newer version active
	 - mod 'Cardinal Components API (blocks)' (cardinal-components-block) 3.0.0, reason: newer version active
	 - mod 'Cardinal Components API (entities)' (cardinal-components-entity) 3.0.0-nightly.1.17-pre1, reason: newer version active
	 - mod 'Cardinal Components API (entities)' (cardinal-components-entity) 3.0.0-nightly.1.17-pre2, reason: newer version active
	 - mod 'Cardinal Components API (entities)' (cardinal-components-entity) 3.0.0, reason: newer version active
	 - mod 'Cardinal Components API (utilities)' (cardinal-components-util) 3.0.0-nightly.1.17-pre2, reason: newer version active
	 - mod 'Cardinal Components API (worlds)' (cardinal-components-world) 3.0.0, reason: newer version active
	 - mod 'Cloth Basic Math' (cloth-basic-math) 0.5.1, reason: newer version active
	 - mod 'Cloth Common Events v1' (cloth-common-events-v1) 1.5.47, reason: newer version active
	 - mod 'Cloth Config v6' (cloth-config) 6.1.48, reason: unknown
	 - mod 'Cloth Config v4' (cloth-config2) 4.11.18, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 5.0.33, reason: newer version active
	 - mod 'Cloth Config v4' (cloth-config2) 5.0.34, reason: newer version active
	 - mod 'Cloth Config v5' (cloth-config2) 5.0.38, reason: newer version active
	 - mod 'Cloth Scissors API v1' (cloth-scissors-api-v1) 2.0.54, reason: wrong environment (client/server only)
	 - mod 'core' (com_electronwill_night-config_core) 3.6.2, reason: newer version active
	 - mod 'core' (com_electronwill_night-config_core) 3.6.3, reason: newer version active
	 - mod 'core' (com_electronwill_night-config_core) 3.6.5, reason: same version active
	 - mod 'toml' (com_electronwill_night-config_toml) 3.6.2, reason: newer version active
	 - mod 'toml' (com_electronwill_night-config_toml) 3.6.3, reason: newer version active
	 - mod 'toml' (com_electronwill_night-config_toml) 3.6.5, reason: same version active
	 - mod 'toml4j' (com_moandjiezana_toml_toml4j) +, reason: newer version active
	 - mod 'Custom Portal Api' (customportalapi) 0.0.1-beta45-1.17, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.1.3+12a8474cfa, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.1.3+12a8474c34, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b446318, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b446313, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b446318, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.0+5847535018, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.0+cf39a74318, reason: same version active
	 - mod 'Fabric BlockRenderLayer Registration (v1)' (fabric-blockrenderlayer-v1) 1.1.6+cf39a74318, reason: wrong environment (client/server only)
	 - mod 'Fabric Command API (v1)' (fabric-command-api-v1) 1.1.2+6cefd57718, reason: newer version active
	 - mod 'Fabric Command API (v1)' (fabric-command-api-v1) 1.1.3+5ab9934c18, reason: newer version active
	 - mod 'Fabric Entity Events (v1)' (fabric-entity-events-v1) 1.2.0+8a9f12e018, reason: newer version active
	 - mod 'Fabric Entity Events (v1)' (fabric-entity-events-v1) 1.2.1+077fc48418, reason: newer version active
	 - mod 'Fabric Item API (v1)' (fabric-item-api-v1) 1.2.4+a02b446318, reason: newer version active
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.4+a02b446318, reason: wrong environment (client/server only)
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.6+2a2bb57318, reason: wrong environment (client/server only)
	 - mod 'Fabric Key Bindings (v0)' (fabric-keybindings-v0) 0.2.4+cf39a74318, reason: wrong environment (client/server only)
	 - mod 'Fabric Lifecycle Events (v1)' (fabric-lifecycle-events-v1) 1.4.4+a02b446318, reason: newer version active
	 - mod 'Fabric Models (v0)' (fabric-models-v0) 0.3.1+cf39a74318, reason: wrong environment (client/server only)
	 - mod 'Fabric Networking API (v1)' (fabric-networking-api-v1) 1.0.14+cf39a74318, reason: newer version active
	 - mod 'Fabric Networking (v0)' (fabric-networking-v0) 0.3.2+92519afa13, reason: newer version active
	 - mod 'Fabric Renderer API (v1)' (fabric-renderer-api-v1) 0.4.5+cf39a74318, reason: wrong environment (client/server only)
	 - mod 'Fabric Renderer - Indigo' (fabric-renderer-indigo) 0.4.9+cf39a74318, reason: wrong environment (client/server only)
	 - mod 'Fabric Renderer Registries (v1)' (fabric-renderer-registries-v1) 3.2.6+cf39a74318, reason: wrong environment (client/server only)
	 - mod 'Fabric Rendering (v0)' (fabric-rendering-v0) 1.1.7+cf39a74318, reason: wrong environment (client/server only)
	 - mod 'Fabric Rendering (v1)' (fabric-rendering-v1) 1.6.0+a02b446318, reason: wrong environment (client/server only)
	 - mod 'Fabric Rendering (v1)' (fabric-rendering-v1) 1.10.1+377137cc18, reason: wrong environment (client/server only)
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.7+b7ab612118, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.10+f09604ce18, reason: same version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.5+cf39a74318, reason: wrong environment (client/server only)
	 - mod 'Fabric Tag Extensions (v0)' (fabric-tag-extensions-v0) 1.2.3+cf39a74318, reason: same version active
	 - mod 'Fabric Textures (v0)' (fabric-textures-v0) 1.0.7+cf39a74318, reason: wrong environment (client/server only)
	 - mod 'Hologram API' (hologram-api) 0.2.0+1.17.1, reason: newer version active
	 - mod 'libaddict' (libaddict) 0.3.0, reason: wrong environment (client/server only)
	 - mod 'LibBlockAttributes' (libblockattributes) 0.8.17003, reason: newer version active
	 - mod 'LibBlockAttributes (Core)' (libblockattributes_core) 0.8.17003, reason: newer version active
	 - mod 'LibBlockAttributes (Core)' (libblockattributes_core) 0.9.0, reason: same version active
	 - mod 'LibBlockAttributes (Fluids)' (libblockattributes_fluids) 0.8.17003, reason: newer version active
	 - mod 'LibBlockAttributes (Fluids)' (libblockattributes_fluids) 0.9.0, reason: same version active
	 - mod 'LibBlockAttributes (Items)' (libblockattributes_items) 0.8.17003, reason: newer version active
	 - mod 'LibBlockAttributes (Items)' (libblockattributes_items) 0.9.0, reason: same version active
	 - mod 'LibCapableData' (libcd) 3.0.3+1.16.3, reason: same version active
	 - mod 'LibGui' (libgui) 4.1.0+1.17, reason: newer version active
	 - mod 'LibGui' (libgui) 4.1.1+1.17.1-rc1, reason: newer version active
	 - mod 'LibGui' (libgui) 4.1.2+1.17.1, reason: newer version active
	 - mod 'LibGui' (libgui) 4.1.3+1.17.1, reason: newer version active
	 - mod 'LibGui' (libgui) 4.1.4+1.17.1, reason: newer version active
	 - mod 'LibGui' (libgui) 4.1.6+1.17.1, reason: newer version active
	 - mod 'LibGui' (libgui) 4.2.1+1.17.1, reason: newer version active
	 - mod 'Magna' (magna) 0.4.0-1.17.1, reason: newer version active
	 - mod 'megane-dml-simulacrum' (megane-dml-simulacrum) 5.6.1+1.0.5, reason: unknown
	 - mod 'Myron' (myron) 1.6.1-1.17.1, reason: newer version active
	 - mod 'OmegaConfig' (omega-config) 1.0.4, reason: newer version active
	 - mod 'OmegaConfig' (omega-config) 1.0.4, reason: newer version active
	 - mod 'Packet Tweaker' (packet_tweaker) 0.2.0-1.17-pre1, reason: newer version active
	 - mod 'Patchouli' (patchouli) 1.17.1-56-FABRIC, reason: newer version active
	 - mod 'Patchouli' (patchouli) 1.17.1-56-FABRIC-SNAPSHOT, reason: newer version active
	 - mod 'Fabric Placeholder API' (placeholder-api) 1.0.1+1.17, reason: newer version active
	 - mod 'Pal' (playerabilitylib) 1.3.0-nightly.1.17-pre1, reason: newer version active
	 - mod 'Pal' (playerabilitylib) 1.3.0-nightly.1.17-rc1, reason: newer version active
	 - mod 'Pal' (playerabilitylib) 1.3.0, reason: newer version active
	 - mod 'Pal' (playerabilitylib) 1.4.0, reason: same version active
	 - mod 'Reborn Core' (reborncore) 5.0.11-beta, reason: same version active
	 - mod 'Server Translations API' (server_translations_api) 1.4.5+1.17, reason: newer version active
	 - mod 'Somnus API' (somnus) 0.0.13-1.17.1, reason: newer version active
	 - mod 'Statement Vanilla Compatibility Module' (statement_vanilla_compatibility) 1.0.1+1.14.4-1.15.2, reason: newer version active
	 - mod 'Step Height Entity Attribute' (step-height-entity-attribute) 1.0.0, reason: same version active
	 - mod 'Energy' (team_reborn_energy) 0.1.1, reason: newer version active
	 - mod 'Trinkets' (trinkets) 3.0.4, reason: same version active
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 8 more

```

**Comment by MSandro** [comment]
could it be ModMenu? but for 1.17.1 the latest version is 2.0.14

**Comment by PlanetTeamSpeakk** [comment]
MM is Manningham Mills aka Fabric ASM, it is shadowed in the jar, but Fabric is dumb. I added it as a dependency to fix conflicts with other mods using an older version of it, but that completely broke the mod.
Will be fixed soon.

**Comment by wlm3201** [comment]
Try this.
https://www.curseforge.com/minecraft/mc-mods/shulkerboxtooltip
I've no idea but it works. Super wierd.

**Comment by MarioMastr** [comment]
I tried to compile but i cannot get 3.9.2 how can i do so?

**Comment by PlanetTeamSpeakk** [comment]
> I tried to compile but i cannot get 3.9.2 how can i do so?

Please don't necropost. Make a new issue if you need.
