### ISSUE TITLE
Crashing on server startup 1.19

### ISSUE THREAD

**Issue by zerebos** [PlanetTeamSpeakk/MoreCommands#67]
Was trying to see if the latest version works with current 1.19, it looks like it does not. I tested using only fabric, fabric api, and MoreCommands.

```
$ java -Xmx2G -jar server.jar nogui
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[02:20:07] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.8
[02:20:07] [main/WARN]: Warnings were found!
 - Mod 'MoreCommands' (morecommands) 3.10.1 recommends any version of luckperms, which is missing!
         - You should install any version of luckperms for the optimal experience.
[02:20:07] [main/INFO]: Loading 48 mods:
        - com_github_vatuu_discord-rpc 1.6.2 via morecommands
        - fabric 0.57.0+1.19
        - fabric-api-base 0.4.9+e62f51a3a9 via fabric
        - fabric-api-lookup-api-v1 1.6.7+9ff28f40a9 via fabric
        - fabric-biome-api-v1 9.0.14+b2a4a624a9 via fabric
        - fabric-command-api-v1 1.2.6+f71b366fa9 via fabric
        - fabric-command-api-v2 2.1.2+0d55f585a9 via fabric
        - fabric-commands-v0 0.2.23+df3654b3a9 via fabric
        - fabric-containers-v0 0.1.27+df3654b3a9 via fabric
        - fabric-content-registries-v0 3.2.0+07df213ea9 via fabric
        - fabric-convention-tags-v1 1.0.8+37622d24a9 via fabric
        - fabric-crash-report-info-v1 0.2.3+bd0a0d4aa9 via fabric
        - fabric-data-generation-api-v1 5.1.1+a680b9b4a9 via fabric
        - fabric-dimensions-v1 2.1.28+a6d2f785a9 via fabric
        - fabric-entity-events-v1 1.4.16+9ff28f40a9 via fabric
        - fabric-events-interaction-v0 0.4.26+9ff28f40a9 via fabric
        - fabric-events-lifecycle-v0 0.2.25+df3654b3a9 via fabric
        - fabric-game-rule-api-v1 1.0.19+18990361a9 via fabric
        - fabric-item-api-v1 1.5.4+767db26ea9 via fabric
        - fabric-item-groups-v0 0.3.25+9ff28f40a9 via fabric
        - fabric-lifecycle-events-v1 2.1.0+33fbc738a9 via fabric
        - fabric-loot-api-v2 1.1.0+03a4e568a9 via fabric
        - fabric-loot-tables-v1 1.1.3+9e7660c6a9 via fabric
        - fabric-message-api-v1 1.0.1+513f4a59a9 via fabric
        - fabric-mining-level-api-v1 2.1.10+33fbc738a9 via fabric
        - fabric-networking-api-v1 1.0.27+7fe97409a9 via fabric
        - fabric-networking-v0 0.3.14+df3654b3a9 via fabric
        - fabric-object-builder-api-v1 4.0.7+9ff28f40a9 via fabric
        - fabric-particles-v1 1.0.8+dc39553aa9 via fabric
        - fabric-registry-sync-v0 0.9.17+23c4cfefa9 via fabric
        - fabric-rendering-data-attachment-v1 0.3.12+9ff28f40a9 via fabric
        - fabric-rendering-fluids-v1 3.0.5+9ff28f40a9 via fabric
        - fabric-resource-conditions-api-v1 2.0.9+e62f51a3a9 via fabric
        - fabric-resource-loader-v0 0.5.5+a6d2f785a9 via fabric
        - fabric-screen-handler-api-v1 1.2.6+9ff28f40a9 via fabric
        - fabric-transfer-api-v1 2.0.9+e62f51a3a9 via fabric
        - fabric-transitive-access-wideners-v1 1.1.1+9e7660c6a9 via fabric
        - fabricloader 0.14.8
        - java 17
        - minecraft 1.19
        - mm 2.3 via morecommands
        - morecommands 3.10.1
        - morecommands-api 1.0.1 via morecommands
        - morecommands-compat16 1.0.0 via morecommands
        - morecommands-compat17 1.0.0 via morecommands
        - morecommands-compat18 1.0.0 via morecommands
        - morecommands-compat182 1.0.0 via morecommands
        - morecommands-compat19 1.0.1 via morecommands
[02:20:07] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/opt/minecraft/guccifabric/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[02:20:07] [main/INFO]: Compatibility level set to JAVA_16
[02:20:08] [main/INFO]: [MoreCommands] Queued RAINBOW Formatting and SCROLL ClickEvent$Action for registration.
[02:20:08] [main/INFO]: [MoreCommands] Defined CopySound and EESound using dumps.
[02:20:09] [main/INFO]: [MoreCommands] Registered value RAINBOW on enum net.minecraft.class_124.
[02:20:09] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2248 failed
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.8.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:0.11.0]
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2248 failed
        at net.minecraft.class_2378.<clinit>(class_2378.java:207) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
        ... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2248 failed
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419) ~[fabric-loader-0.14.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.minecraft.class_2378.<clinit>(class_2378.java:207) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
        ... 4 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.minecraft.class_2378.<clinit>(class_2378.java:207) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
        ... 4 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector dropStacks_onStacksDropped(Lnet/minecraft/class_2680;Lnet/minecraft/class_3218;Lnet/minecraft/class_2338;Lnet/minecraft/class_1799;Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2586;Lnet/minecraft/class_1297;Lnet/minecraft/class_1799;)V in morecommands.common_mixins.json:MixinBlock from mod morecommands failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap MoreCommands-refmap.json
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.minecraft.class_2378.<clinit>(class_2378.java:207) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
        ... 4 more
```

**Comment by PlanetTeamSpeakk** [comment]
The latest released version does not support the stable version of 1.19. A version for this is being worked on, for both Forge and Fabric, and progress can be tracked via the architectury branch.

**Comment by zerebos** [comment]
Thanks for the heads up! I'll keep an eye on that branch then.
