### ISSUE TITLE
Crash on latest versions

### ISSUE THREAD

**Issue by MarioMastr** [PlanetTeamSpeakk/MoreCommands#70]
UltimMC version: 0.7.0-custom

Launched instance in online mode

authserver.mojang.com resolves to:
    [51.68.172.243]

session.minecraft.net resolves to:
    [54.172.106.247, 107.20.118.247, 52.72.238.122]

textures.minecraft.net resolves to:
    [13.224.245.46, 13.224.245.93, 13.224.245.112, 13.224.245.82]

api.mojang.com resolves to:
    [18.172.153.35, 18.172.153.32, 18.172.153.63, 18.172.153.104]

Minecraft folder is:
/Applications/UltimMC.app/Data/instances/1.19.2/.minecraft

Java path is:
/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/bin/java

Checking Java version...
Java is version 17.0.2, using 64-bit architecture, from Azul Systems, Inc..

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  /Applications/UltimMC.app/Data/instances/1.19.2/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  /Applications/UltimMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  /Applications/UltimMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  /Applications/UltimMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  /Applications/UltimMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  /Applications/UltimMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  /Applications/UltimMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  /Applications/UltimMC.app/Data/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  /Applications/UltimMC.app/Data/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  /Applications/UltimMC.app/Data/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /Applications/UltimMC.app/Data/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /Applications/UltimMC.app/Data/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  /Applications/UltimMC.app/Data/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  /Applications/UltimMC.app/Data/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  /Applications/UltimMC.app/Data/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  /Applications/UltimMC.app/Data/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.16.0/log4j-slf4j18-impl-2.16.0.jar
  /Applications/UltimMC.app/Data/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  /Applications/UltimMC.app/Data/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  /Applications/UltimMC.app/Data/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /Applications/UltimMC.app/Data/libraries/io/netty/netty-common/4.1.77.Final/netty-common-4.1.77.Final.jar
  /Applications/UltimMC.app/Data/libraries/io/netty/netty-buffer/4.1.77.Final/netty-buffer-4.1.77.Final.jar
  /Applications/UltimMC.app/Data/libraries/io/netty/netty-codec/4.1.77.Final/netty-codec-4.1.77.Final.jar
  /Applications/UltimMC.app/Data/libraries/io/netty/netty-handler/4.1.77.Final/netty-handler-4.1.77.Final.jar
  /Applications/UltimMC.app/Data/libraries/io/netty/netty-resolver/4.1.77.Final/netty-resolver-4.1.77.Final.jar
  /Applications/UltimMC.app/Data/libraries/io/netty/netty-transport/4.1.77.Final/netty-transport-4.1.77.Final.jar
  /Applications/UltimMC.app/Data/libraries/io/netty/netty-transport-native-unix-common/4.1.77.Final/netty-transport-native-unix-common-4.1.77.Final.jar
  /Applications/UltimMC.app/Data/libraries/io/netty/netty-transport-classes-epoll/4.1.77.Final/netty-transport-classes-epoll-4.1.77.Final.jar
  /Applications/UltimMC.app/Data/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /Applications/UltimMC.app/Data/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  /Applications/UltimMC.app/Data/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /Applications/UltimMC.app/Data/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /Applications/UltimMC.app/Data/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /Applications/UltimMC.app/Data/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  /Applications/UltimMC.app/Data/libraries/com/mojang/datafixerupper/5.0.28/datafixerupper-5.0.28.jar
  /Applications/UltimMC.app/Data/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  /Applications/UltimMC.app/Data/libraries/com/mojang/authlib/3.11.49/authlib-3.11.49.jar
  /Applications/UltimMC.app/Data/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  /Applications/UltimMC.app/Data/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /Applications/UltimMC.app/Data/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /Applications/UltimMC.app/Data/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  /Applications/UltimMC.app/Data/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  /Applications/UltimMC.app/Data/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  /Applications/UltimMC.app/Data/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  /Applications/UltimMC.app/Data/libraries/com/mojang/text2speech/1.13.9/text2speech-1.13.9.jar
  /Applications/UltimMC.app/Data/libraries/ca/weblite/java-objc-bridge/1.1/java-objc-bridge-1.1.jar
  /Applications/UltimMC.app/Data/libraries/net/fabricmc/intermediary/1.19.2/intermediary-1.19.2.jar
  /Applications/UltimMC.app/Data/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  /Applications/UltimMC.app/Data/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar
  /Applications/UltimMC.app/Data/libraries/net/fabricmc/tiny-remapper/0.8.2/tiny-remapper-0.8.2.jar
  /Applications/UltimMC.app/Data/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  /Applications/UltimMC.app/Data/libraries/org/ow2/asm/asm/9.3/asm-9.3.jar
  /Applications/UltimMC.app/Data/libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar
  /Applications/UltimMC.app/Data/libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar
  /Applications/UltimMC.app/Data/libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar
  /Applications/UltimMC.app/Data/libraries/org/ow2/asm/asm-util/9.3/asm-util-9.3.jar
  /Applications/UltimMC.app/Data/libraries/net/fabricmc/fabric-loader/0.14.9/fabric-loader-0.14.9.jar
  /Applications/UltimMC.app/Data/libraries/com/mojang/minecraft/1.19.2/minecraft-1.19.2-client.jar

Native libraries:
  /Applications/UltimMC.app/Data/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-macos.jar
  /Applications/UltimMC.app/Data/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-macos.jar
  /Applications/UltimMC.app/Data/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-macos.jar
  /Applications/UltimMC.app/Data/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-macos.jar
  /Applications/UltimMC.app/Data/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-macos.jar
  /Applications/UltimMC.app/Data/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1-natives-macos.jar
  /Applications/UltimMC.app/Data/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-macos.jar

Mods:
  [❌] advancementinfo-1.19.1-fabric0.58.5-1.3.1.jar.disabled (disabled)
  [❌] animatica-0.5+1.19.jar.disabled (disabled)
  [❌] antighost-1.19.1-fabric0.58.5-1.1.5.jar.disabled (disabled)
  [❌] bettermounthud-1.1.4.jar.disabled (disabled)
  [❌] borderless-mining-1.1.5+1.19.jar.disabled (disabled)
  [❌] Capes-1.4.4+1.19.jar.disabled (disabled)
  [❌] cem-0.7.1.jar.disabled (disabled)
  [❌] CITResewn-1.1.1+1.19.jar.disabled (disabled)
  [❌] colormatic-3.1.2+mc.1.19.jar.disabled (disabled)
  [❌] continuity-2.0.1+1.19.jar.disabled (disabled)
  [❌] CullLessLeaves-1.0.4.jar.disabled (disabled)
  [❌] CustomSkinLoader_Fabric-14.14-SNAPSHOT-343.jar.disabled (disabled)
  [❌] Debugify-2.4.1.jar.disabled (disabled)
  [❌] dynamic-fps-2.2.0.jar.disabled (disabled)
  [❌] enhancedblockentities-0.7.1+1.19.jar.disabled (disabled)
  [❌] entity_texture_features_fabric_1.19.x-4.0.2.jar.disabled (disabled)
  [❌] entityculling-fabric-1.5.2-mc1.19.jar.disabled (disabled)
  [❌] essential_commands-0.28.1-mc1.19.2.jar.disabled (disabled)
  [✔️] fabric-api-0.60.0+1.19.2.jar
  [❌] fabric-language-kotlin-1.8.2+kotlin.1.7.10.jar.disabled (disabled)
  [❌] fabrishot-1.8.0.jar.disabled (disabled)
  [❌] ferritecore-5.0.0-fabric.jar.disabled (disabled)
  [❌] Gamma-Utils-1.6.10-mc1.19.2.jar.disabled (disabled)
  [❌] holdthatchunk-1.0.3+1.18.jar.disabled (disabled)
  [❌] indium-1.0.7+mc1.19.jar.disabled (disabled)
  [❌] iris-mc1.19.1-1.2.6.jar.disabled (disabled)
  [❌] item-model-fix-1.0.3+1.19.jar.disabled (disabled)
  [❌] lambdabettergrass-1.3.0+1.19.jar.disabled (disabled)
  [❌] lambdynamiclights-2.1.2+1.19.jar.disabled (disabled)
  [❌] language-reload-1.3.2.jar.disabled (disabled)
  [❌] lazydfu-0.1.3.jar.disabled (disabled)
  [❌] litematica-fabric-1.19.2-0.12.4.jar.disabled (disabled)
  [❌] lithium-fabric-mc1.19.2-0.8.3.jar.disabled (disabled)
  [❌] main-menu-credits-1.1.1.jar.disabled (disabled)
  [❌] malilib-fabric-1.19.2-0.13.0.jar.disabled (disabled)
  [❌] memoryleakfix-1.19.1-0.7.0.jar.disabled (disabled)
  [❌] midnightcontrols-1.5.0+1.19.jar.disabled (disabled)
  [❌] minihud-fabric-1.19.2-0.23.3.jar.disabled (disabled)
  [❌] MixinConflictHelper-1.1.0.jar.disabled (disabled)
  [❌] mixintrace-1.1.1+1.17.jar.disabled (disabled)
  [❌] modmenu-4.0.6.jar.disabled (disabled)
  [❌] morechathistory-1.19.1-1.1.1.jar.disabled (disabled)
  [✔️] MoreCommands-3.10.1_1.16.4-22w16b.jar
  [❌] NoChatReports-FABRIC-1.19.2-v1.9.1.jar.disabled (disabled)
  [❌] nofade-1.18-2.0.1.jar.disabled (disabled)
  [❌] ok_zoomer-5.0.0-beta.9+1.19.jar.disabled (disabled)
  [❌] optigui-1.1.1.jar.disabled (disabled)
  [❌] puzzle-1.4.0-1.19.jar.disabled (disabled)
  [❌] qfapi-4.0.0-beta.9_qsl-3.0.0-beta.14_fapi-0.60.0_mc-1.19.2.jar.disabled (disabled)
  [❌] reeses_sodium_options-1.4.6+mc1.19.2-build.55.jar.disabled (disabled)
  [❌] smoothboot-fabric-1.19-1.7.1.jar.disabled (disabled)
  [❌] sodium-extra-0.4.6+mc1.19-build.47.jar.disabled (disabled)
  [❌] sodium-fabric-mc1.19-0.4.2+build.16.jar.disabled (disabled)
  [❌] starlight-1.1.1+fabric.ae22326.jar.disabled (disabled)
  [❌] tooltipfix-1.0.5-1.19.jar.disabled (disabled)
  [❌] tweakeroo-fabric-1.19.2-0.14.3.jar.disabled (disabled)
  [❌] yosbr-0.1.1.jar.disabled (disabled)
  [❌] Zoomify-2.0.3.jar.disabled (disabled)

Params:
  --username  --version 1.19.2 --gameDir /Applications/UltimMC.app/Data/instances/1.19.2/.minecraft --assetsDir /Applications/UltimMC.app/Data/assets --assetIndex 1.19 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-javaagent:/Applications/UltimMC.app/Data/injectors/authlib-injector-1.2.1.jar=http://localhost:56586, -Dauthlibinjector.noShowServerName, -Xdock:icon=icon.png, -Xdock:name="UltimMC: 1.19.2", -XstartOnFirstThread, -Xms1024m, -Xmx4096m, -Duser.language=en]

Wrapper command is:
/Users/ashrafmohamed/Minecraft/m1-multimc-hack/mcwrap.py

Minecraft process ID: 20038

[authlib-injector] [INFO] Logging file: /Applications/UltimMC.app/Data/instances/1.19.2/.minecraft/authlib-injector.log
[authlib-injector] [INFO] Version: 1.2.1
[authlib-injector] [INFO] Authentication server: http://localhost:56586
[authlib-injector] [WARNING] You are using HTTP protocol, which is INSECURE! Please switch to HTTPS if possible.
Using onesix launcher.

[20:18:03] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.9
[20:18:04] [main/WARN]: Warnings were found!
 - Mod 'MoreCommands' (morecommands) 3.10.1 recommends any version of luckperms, which is missing!
	 - You should install any version of luckperms for the optimal experience.
[20:18:04] [main/INFO]: Loading 60 mods:
	- com_github_vatuu_discord-rpc 1.6.2 via morecommands
	- fabric-api 0.60.0+1.19.2
	- fabric-api-base 0.4.11+e62f51a390 via fabric-api
	- fabric-api-lookup-api-v1 1.6.9+9ff28f4090 via fabric-api
	- fabric-biome-api-v1 9.0.17+aeb40ebe90 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.20+aeb40ebe90 via fabric-api
	- fabric-client-tags-api-v1 1.0.1+b35fea8390 via fabric-api
	- fabric-command-api-v1 1.2.11+f71b366f90 via fabric-api
	- fabric-command-api-v2 2.1.7+0c17ea9690 via fabric-api
	- fabric-commands-v0 0.2.28+df3654b390 via fabric-api
	- fabric-containers-v0 0.1.34+df3654b390 via fabric-api
	- fabric-content-registries-v0 3.2.3+aeb40ebe90 via fabric-api
	- fabric-convention-tags-v1 1.1.1+7cd20a1490 via fabric-api
	- fabric-crash-report-info-v1 0.2.5+aeb40ebe90 via fabric-api
	- fabric-data-generation-api-v1 5.1.8+a680b9b490 via fabric-api
	- fabric-dimensions-v1 2.1.30+aeb40ebe90 via fabric-api
	- fabric-entity-events-v1 1.4.18+9ff28f4090 via fabric-api
	- fabric-events-interaction-v0 0.4.28+aeb40ebe90 via fabric-api
	- fabric-events-lifecycle-v0 0.2.28+df3654b390 via fabric-api
	- fabric-game-rule-api-v1 1.0.21+aeb40ebe90 via fabric-api
	- fabric-item-api-v1 1.5.7+35a03c4390 via fabric-api
	- fabric-item-groups-v0 0.3.28+aeb40ebe90 via fabric-api
	- fabric-key-binding-api-v1 1.0.20+aeb40ebe90 via fabric-api
	- fabric-keybindings-v0 0.2.18+df3654b390 via fabric-api
	- fabric-lifecycle-events-v1 2.1.2+aeb40ebe90 via fabric-api
	- fabric-loot-api-v2 1.1.3+83a8659290 via fabric-api
	- fabric-loot-tables-v1 1.1.6+9e7660c690 via fabric-api
	- fabric-message-api-v1 5.0.3+176380a290 via fabric-api
	- fabric-mining-level-api-v1 2.1.14+33fbc73890 via fabric-api
	- fabric-models-v0 0.3.17+aeb40ebe90 via fabric-api
	- fabric-networking-api-v1 1.2.4+5eb68ef290 via fabric-api
	- fabric-networking-v0 0.3.21+df3654b390 via fabric-api
	- fabric-object-builder-api-v1 4.0.11+aeb40ebe90 via fabric-api
	- fabric-particles-v1 1.0.10+aeb40ebe90 via fabric-api
	- fabric-registry-sync-v0 0.9.24+aeb40ebe90 via fabric-api
	- fabric-renderer-api-v1 1.0.10+aeb40ebe90 via fabric-api
	- fabric-renderer-indigo 0.6.12+aeb40ebe90 via fabric-api
	- fabric-renderer-registries-v1 3.2.20+df3654b390 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.14+aeb40ebe90 via fabric-api
	- fabric-rendering-fluids-v1 3.0.7+aeb40ebe90 via fabric-api
	- fabric-rendering-v0 1.1.22+df3654b390 via fabric-api
	- fabric-rendering-v1 1.10.16+aeb40ebe90 via fabric-api
	- fabric-resource-conditions-api-v1 2.0.11+e62f51a390 via fabric-api
	- fabric-resource-loader-v0 0.6.1+aeb40ebe90 via fabric-api
	- fabric-screen-api-v1 1.0.26+f05effaf90 via fabric-api
	- fabric-screen-handler-api-v1 1.2.13+9ff28f4090 via fabric-api
	- fabric-textures-v0 1.0.20+aeb40ebe90 via fabric-api
	- fabric-transfer-api-v1 2.0.11+83a8659290 via fabric-api
	- fabric-transitive-access-wideners-v1 1.3.0+42d99c3290 via fabric-api
	- fabricloader 0.14.9
	- java 17
	- minecraft 1.19.2
	- mm 2.3 via morecommands
	- morecommands 3.10.1
	- morecommands-api 1.0.1 via morecommands
	- morecommands-compat16 1.0.0 via morecommands
	- morecommands-compat17 1.0.0 via morecommands
	- morecommands-compat18 1.0.0 via morecommands
	- morecommands-compat182 1.0.0 via morecommands
	- morecommands-compat19 1.0.1 via morecommands
[20:18:04] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/Applications/UltimMC.app/Data/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[20:18:04] [main/INFO]: Compatibility level set to JAVA_16
[20:18:05] [main/INFO]: [MoreCommands] Queued RAINBOW Formatting and SCROLL ClickEvent$Action for registration.
[20:18:05] [main/INFO]: [MoreCommands] Defined CopySound and EESound using dumps.
[authlib-injector] [INFO] Transformed [net.minecraft.client.main.Main] with [Main Arguments Transformer]
[20:18:06] [main/INFO]: [MoreCommands] Registered value RAINBOW on enum net.minecraft.class_124.
[20:18:06] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[20:18:06] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[authlib-injector] [INFO] Transformed [net.minecraft.client.main.Main] with [Main Arguments Transformer]
[20:18:07] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2248 failed
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2248 failed
	at net.minecraft.class_2378.<clinit>(class_2378.java:207) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:161) ~[minecraft-1.19.2-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 10 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2248 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:207) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:161) ~[minecraft-1.19.2-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:207) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:161) ~[minecraft-1.19.2-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 10 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector dropStacks_onStacksDropped(Lnet/minecraft/class_2680;Lnet/minecraft/class_3218;Lnet/minecraft/class_2338;Lnet/minecraft/class_1799;Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2586;Lnet/minecraft/class_1297;Lnet/minecraft/class_1799;)V in morecommands.common_mixins.json:MixinBlock from mod morecommands failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap MoreCommands-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:207) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:161) ~[minecraft-1.19.2-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 10 more
Process exited with code 0 (0x0).

**Comment by PlanetTeamSpeakk** [comment]
The current stable version of the mod does not support 1.19.2
