### ISSUE TITLE
Crashing on version 4.0, MC Forge 43.2.0 when using Pehkui

### ISSUE THREAD

**Issue by buckywuckii** [PlanetTeamSpeakk/MoreCommands#93]
Exactly as the title says. We already discussed this issue earlier, just putting it here so you don't forget about it! :)

**Comment by MSandro** [comment]
same issue on Fabric 1.18.2
<details><summary>latest.log</summary>
<p>
[14:49:44] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.19
[14:49:44] [main/WARN]: Warnings were found!
 - Mod 'MoreCommands' (morecommands) 4.0 recommends any version of luckperms, which is missing!
	 - You should install any version of luckperms for the optimal experience.
[14:49:44] [main/INFO]: Loading 72 mods:
	- architectury 4.11.90
	- cloth-config 6.4.90
	   \-- cloth-basic-math 0.6.1
	- fabric-api 0.76.0+1.18.2
	   |-- fabric-api-base 0.4.5+64b7c69360
	   |-- fabric-api-lookup-api-v1 1.6.3+2373a54560
	   |-- fabric-biome-api-v1 8.0.7+e83becad60
	   |-- fabric-block-api-v1 1.0.0+ee3621fc60
	   |-- fabric-blockrenderlayer-v1 1.1.13+3ac43d9560
	   |-- fabric-command-api-v1 1.1.10+d7c144a860
	   |-- fabric-commands-v0 0.2.9+b4f4f6cd60
	   |-- fabric-containers-v0 0.1.24+d7c144a860
	   |-- fabric-content-registries-v0 3.1.3+c85f2e3860
	   |-- fabric-convention-tags-v1 1.1.0+43ce63a460
	   |-- fabric-crash-report-info-v1 0.2.1+ee261a3e60
	   |-- fabric-data-generation-api-v1 3.1.0+6c70b68e60
	   |-- fabric-dimensions-v1 2.1.21+489d6f8260
	   |-- fabric-entity-events-v1 1.4.9+d7c144a860
	   |-- fabric-events-interaction-v0 0.4.20+d7c144a860
	   |-- fabric-events-lifecycle-v0 0.2.22+d7c144a860
	   |-- fabric-game-rule-api-v1 1.0.13+d7c144a860
	   |-- fabric-item-api-v1 1.6.2+8165403660
	   |-- fabric-item-groups-v0 0.3.16+91896a4960
	   |-- fabric-key-binding-api-v1 1.0.12+54e5b2ec60
	   |-- fabric-keybindings-v0 0.2.10+b4f4f6cd60
	   |-- fabric-lifecycle-events-v1 2.1.1+cc71601c60
	   |-- fabric-loot-api-v2 1.1.2+1997ad1260
	   |-- fabric-loot-tables-v1 1.1.4+e747827960
	   |-- fabric-mining-level-api-v1 2.1.6+cc71601c60
	   |-- fabric-models-v0 0.3.7+d7c144a860
	   |-- fabric-networking-api-v1 1.0.24+2d30af4b60
	   |-- fabric-networking-v0 0.3.11+b4f4f6cd60
	   |-- fabric-object-builder-api-v1 2.1.5+032c981d60
	   |-- fabric-particles-v1 0.2.13+526dc1ac60
	   |-- fabric-registry-sync-v0 0.9.12+bb2e047760
	   |-- fabric-renderer-api-v1 0.5.0+bf48649860
	   |-- fabric-renderer-indigo 0.6.1+03e2b68760
	   |-- fabric-renderer-registries-v1 3.2.12+b4f4f6cd60
	   |-- fabric-rendering-data-attachment-v1 0.3.9+ee3621fc60
	   |-- fabric-rendering-fluids-v1 2.0.3+54e5b2ec60
	   |-- fabric-rendering-v0 1.1.14+b4f4f6cd60
	   |-- fabric-rendering-v1 1.10.8+54e5b2ec60
	   |-- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660
	   |-- fabric-resource-loader-v0 0.5.3+047a5ecb60
	   |-- fabric-screen-api-v1 1.0.11+d882b91560
	   |-- fabric-screen-handler-api-v1 1.2.3+1f6558e860
	   |-- fabric-textures-v0 1.0.13+3ac43d9560
	   |-- fabric-transfer-api-v1 1.6.4+f4563ac860
	   \-- fabric-transitive-access-wideners-v1 1.1.0+e747827960
	- fabricloader 0.14.19
	- farmersdelight 1.18.2-1.2.5
	- java 17
	- minecraft 1.18.2
	- modern_industrialization 1.2.3
	   |-- magna 1.7.0-1.18-pre1
	   |-- noindium 1.0.2+1.18.2
	   |    \-- omega-config 1.2.3-1.18.1
	   |-- playerabilitylib 1.5.0
	   \-- team_reborn_energy 2.2.0
	- morecommands 4.0
	- patchouli 1.18.2-71.1-FABRIC
	   \-- fiber 0.23.0-2
	- pehkui 3.7.4+1.14.4-1.20
	   \-- kanos_config 0.4.1+1.14.4-1.19.4
	- reborncore 5.2.1
	   \-- team_reborn_energy 2.2.0
	- roughlyenoughitems 8.3.594
	   \-- error_notifier 1.0.9
	- techreborn 5.2.1
	   \-- team_reborn_energy 2.2.0
	- theoneprobe 1.18-5.1.3
	   |-- forgeconfigapiport 3.2.0
	   |    |-- com_electronwill_night-config_core 3.6.3
	   |    \-- com_electronwill_night-config_toml 3.6.3
	   \-- team_reborn_energy 2.2.0
[14:49:44] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/sandro/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[14:49:44] [main/INFO]: Compatibility level set to JAVA_16
[14:49:44] [main/INFO]: Compatibility level set to JAVA_17
[14:49:47] [main/WARN]: @ModifyConstant conflict. Skipping pehkui.mixins.json:reach.ScreenHandlerMixin from mod pehkui->@ModifyConstant::pehkui$canUse$distance(DLnet/minecraft/class_2248;Lnet/minecraft/class_1657;)D with priority 1000, already redirected by fabric-morecommands_reach.mixins.json:common.MixinScreenHandler from mod morecommands->@ModifyConstant::method_17696_maxReach(DLnet/minecraft/class_2248;Lnet/minecraft/class_1657;Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;)D with priority 1000
[14:49:47] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:464) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.19.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[client-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[client-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[minecraft-1.18.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	... 5 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1703 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:261) ~[client-intermediary.jar:?]
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[client-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[client-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[minecraft-1.18.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	... 5 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:261) ~[client-intermediary.jar:?]
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[client-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[client-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[minecraft-1.18.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	... 5 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method pehkui$canUse$distance(DLnet/minecraft/class_2248;Lnet/minecraft/class_1657;)D in pehkui.mixins.json:reach.ScreenHandlerMixin from mod pehkui failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap Pehkui-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.
java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:261) ~[client-intermediary.jar:?]
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[client-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[client-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[minecraft-1.18.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	... 5 more
Process exited with code 1.


</p>
</details>
