### ISSUE TITLE
Server crashes when morecommands is running onlyserver mode on create astral

### ISSUE THREAD

**Issue by weeaudi** [PlanetTeamSpeakk/MoreCommands#96]
```
---- Minecraft Crash Report ----
// You're mean.

Time: 7/25/23, 5:10 PM
Description: Exception in server tick loop

java.lang.IllegalStateException: Some intrusive holders were not added to registry: [Reference{null=Block{minecraft:air}}]
	at net.minecraft.class_2370.method_40276(class_2370.java:330)
	at net.minecraft.class_2378.method_40292(class_2378.java:369)
	at net.minecraft.server.MinecraftServer.handler$cbb001$beforeSetupServer(MinecraftServer.java:9803)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 6.1.34-Unraid
	Java Version: 18.0.2.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 1647800632 bytes (1571 MiB) / 3321888768 bytes (3168 MiB) up to 15728640000 bytes (15000 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
	Identifier: Intel64 Family 6 Model 44 Stepping 2
	Microarchitecture: Westmere (Server)
	Frequency (GHz): 2.67
	Number of physical packages: 2
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 72362.72
	Virtual memory used (MB): 28115.02
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms128M -Xmx15000M
	Fabric Mods: 
		ad_astra: Ad Astra 1.0.9
			team_reborn_energy: Energy 2.2.0
		adoptafloppa: Adopt a Floppa 1.1.0
		ae2: Applied Energistics 2 11.7.1
		alternate-current: Alternate Current 1.4.0
		another_furniture: Another Furniture 1.2.2-1.18.2
		appleskin: AppleSkin 2.4.1+mc1.18.2
		architectury: Architectury 4.11.90
		astralvinery: AstralVinery 1.1.1
		autoconfig1u: Auto Config v1 Updated 3.4.0
		automobility: Automobility 0.3+1.18.2
			jsonem: JsonEM 0.1.2
			myron: Myron 1.6.3+1.18.1
		badpackets: Bad Packets 0.1.3
		balm-fabric: Balm 3.2.1+0
		betteradvancements: Better Advancements 0.2.0.146
		bettercombat: Better Combat 1.6.2+1.18.2
		campanion: Campanion 3.0.3
		camsbackpacks: Cammie's Wearable Backpacks 2.2
		cardinal-components: Cardinal Components API 4.2.0
			cardinal-components-base: Cardinal Components API (base) 4.2.0
			cardinal-components-block: Cardinal Components API (blocks) 4.2.0
			cardinal-components-chunk: Cardinal Components API (chunks) 4.2.0
			cardinal-components-entity: Cardinal Components API (entities) 4.2.0
			cardinal-components-item: Cardinal Components API (items) 4.2.0
			cardinal-components-level: Cardinal Components API (world saves) 4.2.0
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 4.2.0
			cardinal-components-world: Cardinal Components API (worlds) 4.2.0
		carpet: Carpet Mod 1.4.69
		catwalksinc: Catwalks Inc. 1.3.0
		cccbridge: CC:C Bridge 1.3.1
		chassis: Chassis 1.1.0
		chipped: Chipped 2.0.1
		chunky: Chunky 1.2.164
		cloth-config: Cloth Config v6 6.4.90
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 8.0.0+17
		cobblegen: CobbleGen v2.1b57-BETA
			blue_endless_jankson: jankson 1.2.1
		companion: Companion 2.0.1
		completeconfig: CompleteConfig 1.4.1
		compressor: Compressor 0.2.0
			crowdin-translate: CrowdinTranslate 1.4+1.18.2
		computercraft: CC: Restitched 1.100.8
			cloth-utils-v1: Cloth Utils v1 2.0.54
		cookingforblockheads: Cooking for Blockheads 12.2.0
		create: Create 0.5.0.i-988+1.18.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			forge_tags: Forge Tags 2.1
			milk: Milk Lib 0.3.2
				dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0
			porting_lib: Porting Lib 1.2.869-beta+1.18.2
			registrate-fabric: Registrate for Fabric MC1.18.2-1.1.11
		createaddition: Create Crafts & Additions 20230211a
		createdeco: Create Deco 1.2.13-1.18.2
		createsifter: Create Sifter ${version}
		custommachinery: Custom Machinery 0.7.6
		cyber-permissions: CyberPermissions 1.5
			itext-lib: iTextLib 1.18-v1
		datapackportals: Datapack Portals 1.1.1-1.18
			customportalapi: Custom Portal Api 0.0.1-beta50-1.18
		dbe: Dave's Building Extended 1.18.2-1.0.0
		debugify: Debugify 1.11.0
		disableportals: Disable Portals 0.2.0-1.18-pre5
		doodads: Doodads 0.1.2-1.18.2
		drinkbeer: Drink Beer 3.2.0
		dustrial_decor: Dustrial Decor 0.5
		environmentalcreepers: Environmental Creepers 1.6.0
		explorerscompass: Explorer's Compass 1.18.2-2.2.0-fabric
		extractinator: Extractinator 2.0.1
			resourcefullib: Resourceful Lib 0.0.4
		fabric-api: Fabric API 0.76.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.5+64b7c69360
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.3+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.7+e83becad60
			fabric-block-api-v1: Fabric Block API (v1) 1.0.0+ee3621fc60
			fabric-command-api-v1: Fabric Command API (v1) 1.1.10+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.9+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.24+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.3+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.0+43ce63a460
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.1.0+6c70b68e60
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.21+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.9+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.20+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.22+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.6.2+8165403660
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.16+91896a4960
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.1+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.2+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.6+cc71601c60
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.24+2d30af4b60
			fabric-networking-v0: Fabric Networking (v0) 0.3.11+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.5+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.13+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.12+bb2e047760
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.9+ee3621fc60
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.3+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.3+047a5ecb60
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.3+1f6558e860
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.4+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.9.3+kotlin.1.8.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.0
		fabricloader: Fabric Loader 0.14.14
		farmersdelight: Farmer's Delight 1.18.2-1.2.5
		fastfurnace: FastFurnace 1.18.2-4.1
		ferritecore: FerriteCore 4.2.1
		forgeconfigapiport: Forge Config API Port 3.2.4
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		ftbbackups2: FTB Backups 2 1.0.18
		ftbchunks: FTB Chunks 1802.3.16-build.247
		ftblibrary: FTB Library 1802.3.11-build.177
		ftbquests: FTB Quests 1802.3.14-build.191
		ftbteams: FTB Teams 1802.2.10-build.96
		gearreborn: Gear Reborn 1.18.2-0.1.14
		geckolib3: Geckolib 3.0.80
			com_eliotlash_mclib_mclib: mclib 20
		globaldataandresourcepacks: Global Data- & Resourcepacks 1.12.3_fabric
		harvestwithease: Harvest with ease 4.0.0.2
		iceberg: Iceberg 1.0.38
		idwtialsimmoedm: idwtialsimmoedm 0.1.1+1.18
		immersive_aircraft: Immersive Aircraft 0.3.0+1.18.2
		itemfilters: Item Filters 1802.2.8-build.47
		jade: Jade 5.99.10
		jadeaddons: Jade Addons 2.0.1
		java: OpenJDK 64-Bit Server VM 18
		jmi: JourneyMapIntegration 0.13-32
		journeymap-fabric: Journeymap 5.9.4
			journeymap-api-fabric: JourneyMap API 1.18.2-1.9-fabric-SNAPSHOT
		konkrete: Konkrete 1.6.0
		krypton: Krypton 0.1.9
			com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		kubejs: KubeJS 1802.5.5-build.567
		kubejs_create: KubeJS Create 1802.2.2-build.28
		lazydfu: LazyDFU 0.1.2
		letmedespawn: Let Me Despawn fabric-1.0.2
		limitedchunks: Limited Chunkloading Mod 1.18.2-2.5
		lithium: Lithium 0.10.3
		lootr: Lootr 0.3.24.61
		luckperms: LuckPerms 5.4.25
		mcdw: MC Dungeons Weapons 5.0.4-1.18
			enchant_giver: Enchant Giver 1.2.1
			reach-entity-attributes: Reach Entity Attributes 2.2.0
		memoryleakfix: Memory Leak Fix 1.0.0
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.6
		midnightlib: MidnightLib 0.4.4
		minecraft: Minecraft 1.18.2
		mixintrace: MixinTrace 1.1.1+1.17
		morecommands: MoreCommands 3.10.1
			com_github_vatuu_discord-rpc: discord-rpc 1.6.2
			mm: Manningham Mills 2.3
			morecommands-api: MoreCommands API 1.0.1
			morecommands-compat16: MoreCommands Compat16 1.0.0
			morecommands-compat17: MoreCommands Compat17 1.0.0
			morecommands-compat18: MoreCommands Compat18 1.0.0
			morecommands-compat182: MoreCommands Compat182 1.0.0
			morecommands-compat19: MoreCommands Compat19 1.0.1
		mysticaloaktree: Mystical Oak Tree 1.18.2-1.0
		naturalist: Naturalist 1.1.1
		notrade: Disable Villager Trades 0.1.1.18.2
		packages: Packages 3.4
		packed-inventory: Packed Inventory 0.2.2+1.18.2
		passivepiglins: Passive Piglins 1.0.1
		per_aspera: Per Aspera 1.3.2
		phonos: Phonos 0.3+1.18.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.5.7
			libgui: LibGui 5.2.0+1.18
				jankson: Jankson 4.0.0+j1.2.0
				libninepatch: LibNinePatch 1.1.0
		ping-wheel: Ping Wheel 1.2.0
		player-animator: Player Animator 1.0.2+1.18
		polaroidcamera: PolaroidCamera 1.2.9
		polymorph: Polymorph 0.0.21-1.18.2
		projectiledamage: Projectile Damage Attribute 2.2.0+1.18.2
		quarrymod: Industrial Quarry Mod 0.7.3
		questsadditions: Quests Additions 1.4.1
		reinfchest: Reinforced Chests 2.2.0+1.18
			reinfcore: Reinforced Core 3.0.3+1.18
		rhino: Rhino 1802.2.1-build.255
		roughlyenoughitems: Roughly Enough Items 8.3.588
			error_notifier: Error Notifier 1.0.9
		searchlight: Searchlight 1.1.7
		servercore: ServerCore 1.2.9-1.18.2
			placeholder-api: Placeholder API 1.1.3+1.17.1
		servertick: Server Tick 1.6
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		smoothchunk: Smooth chunk save Mod 1.18.2-1.9
		smwyg: Show Me What You Got 1.0.1
		sniffer: Mobvote 2022 Sniffer 1.1.2
		spark: spark 1.9.11
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		starlight: Starlight 1.0.2+fabric.89b8d9f
		subterrestrial: Subterrestrial 2.0.0
		suggestion_tweaker: Suggestion Tweaker 1.18.2-1.3.0
		t_and_t: Towns and Towers 1.10.0.1
		tconstruct: Hephaestus 1.18.2-3.5.2.155
			mantle: Mantle 1.18.2-1.9.156
				star: Star 1.3+1.18.2
			serialization_hooks: Serialization Hooks 0.3.23
		techreborn: Tech Reborn 5.2.1
			reborncore: Reborn Core 5.2.1
		trinkets: Trinkets 3.3.1
		vinery: Vinery 1.1.4
			terraform-wood-api-v1: Terraform Wood API (v1) 3.1.0
		worldedit: WorldEdit 7.2.10+1742f98
		xlpackets: XLPackets 3.1-1.18.2
		yigd: You're in Grave Danger 1.3.13
	Server Running: true
	Data Packs: vanilla, compressor (incompatible), Fabric Mods, global:AstralRails, global:zLaky Core (incompatible), global:zTConstructAstra (incompatible)
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

```

Server works when more commands is running not in serveronly mode

**Comment by weeaudi** [comment]
Was able to return it back to Server and client mode. (Reason I switched was because I was stuck in a crash loop on my client)
